services:
  svelte:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/mydb
      AUTH_TRUST_HOST: "true"
      PORT: 3000
      HOST: 0.0.0.0
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - uploads_data:/app/uploads
    command: >
      sh -c "bun prisma db push && bun index.js"
    restart: always

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  db_data:
  uploads_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt