name: "CI/CD"

on: [ push, pull_request ]

jobs:
  setup-bun:
    name: Setup Bun and Cache Dependencies
    runs-on: ubuntu-latest
    outputs:
      bun-cache-hit: ${{ steps.cache-dependencies.outputs.cache-hit }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Bun Dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun
            bun.lockb
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Setup Bun
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          curl -fsSL https://bun.sh/install | bash
        shell: bash

      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: ~/.bun/bin/bun install

  es-lint:
    name: Check linting (es-lint)
    needs: [ setup-bun ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ESLint
        run: ~/.bun/bin/bun lint

  svelte:
    name: Test build (svelte)
    needs: [ es-lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Svelte
        run: ~/.bun/bin/bun run build

  deploy:
    name: Deploy (ssh)
    if: |
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      && github.repository_owner == 'averithefox'
      && github.event_name == 'push'
    needs: [ svelte ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~
            if [ ! -d "media.j3rzy.dev" ]; then
              git clone https://github.com/averithefox/media.j3rzy.dev.git
            fi
            cd media.j3rzy.dev
            chmod +x deploy.sh
            ./deploy.sh