name: "CI/CD"

on: [ push ]

env:
  NODE_VERSION: "20"

jobs:
  npm:
    name: install dependencies (bun)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        run: |
          curl -fsSL https://bun.sh/install | bash

      - name: Install dependencies
        run: ~/.bun/bin/bun install

  es-lint:
    name: check linting (es-lint)
    needs: [ npm ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        run: |
          curl -fsSL https://bun.sh/install | bash

      - name: Install dependencies
        run: ~/.bun/bin/bun install

      - name: Check ESLint
        run: ~/.bun/bin/bun lint

  svelte:
    name: test build (svelte)
    needs: [ es-lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        run: |
          curl -fsSL https://bun.sh/install | bash

      - name: Install dependencies
        run: ~/.bun/bin/bun install

      - name: Build Svelte
        run: ~/.bun/bin/bun run build

  deploy:
    name: deploy (ssh)
    if: |
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      && github.repository_owner == 'averithefox'
      && github.event_name == 'push'
    needs: [ svelte ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~
            if [ ! -d "media.j3rzy.dev" ]; then
              git clone https://github.com/averithefox/media.j3rzy.dev.git
            fi
            cd media.j3rzy.dev
            chmod +x deploy.sh
            ./deploy.sh