name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~
            if [ ! -d "media.j3rzy.dev" ]; then
              git clone https://github.com/averithefox/media.j3rzy.dev.git
            fi
            cd media.j3rzy.dev
            chmod +x deploy.sh
            ./deploy.sh